version: '3.7'

networks:
  codigomarret:
    driver: bridge

services:
  mysql:
    image: mysql:5.7.28
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Marret123456+-*
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - 3382:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - codigomarret

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=mysql:3306
      - MYSQL_ROOT_PASSWORD=Marret123456+-*
      - UPLOAD_LIMIT=300M
    depends_on:
      - mysql
    ports:
      - 8085:80
    networks:
      - codigomarret

  whatsapp_qr:
    image: djmarret1992/codigobm-whatsapp-qr-api:dev_a3d3e861
    restart: always
    container_name: whatsapp_qr
    ports:
      - 4203:3000
    networks:
      - codigomarret
    environment:
      - PORT=3000
      - DEV=
      - PROXY=/api_qr/
      - HOST=https://ordenfacil.org
      - MT_HOST=https://ordenfacil.org/api_qr/pdf/
    volumes:
      - whatsapp_qr:/WhatsappQr/auth_info_baileys

  api_ordenfacil:
    image: djmarret1992/codigobm-api-ordenfacil:dev_Bypgiepw
    restart: always
    container_name: api_ordenfacil
    ports:
      - 4201:3000
    networks:
      - codigomarret
    environment:
      - PORT=3000
      - DEV=developmen
      - USER_DB=root
      - PASSWORD_DB=Marret123456+-*
      - DATABASE_DB=facturacion_api
      - HOST_DB=mysql
      - SECRET=awhgedcnqerucvqiuebciqebcdqwygcqucqwejxgq3yrcbq3ce1iyexiqkwjebcq

  fromt_ordenfacil:
    image: djmarret1992/codigobm-fromt-ordenfacil:dev_c92ce83f
    restart: always
    container_name: fromt_ordenfacil
    ports:
      - 4200:80

  fromt_flashchat:
    # image: djmarret1992/flashchat:dev_ab62a3ff
    image: djmarret1992/flashchat:dev_5468097f
    restart: always
    container_name: fromt_flashchat
    ports:
      - 4300:80

  api_facturacion:
    image: djmarret1992/codigobm-api-facturacion:dev_SzkStcLj
    restart: always
    container_name: api_facturacion
    ports:
      - 4204:3000
    networks:
      - codigomarret
    environment:
      - PORT=3000
      - DEV=production
      - USER_DB=root
      - PASSWORD_DB=Marret123456+-*
      - DATABASE_DB=facturacion_api
      - USER_EMAIL=facturacion@ordenfacil.org
      - PASSWORD_EMAIL=facturacion*2023
      - HOST_DB=mysql
      - SECRET=awhgedcnqerucvqiuebciqebcdqwygcqucqwejxgq3yrcbq3ce1iyexiqkwjebcq
    volumes:
      # - ./facturacion:/facturacion/src/facturacion_electronica/facturacion/Firmado/
      - ./firma:/facturacion/src/facturacion_electronica/Firma/

  cron_facturacion:
    image: djmarret1992/codigobm-cron-factura-emite:dev_Y4SeBAob
    restart: always
    container_name: cron_facturacion
    networks:
      - codigomarret
    environment:
      - PORT=3000
      - DEV=production
      - USER_DB=root
      - PASSWORD_DB=Marret123456+-*
      - DATABASE_DB=facturacion_api
      - USER_EMAIL=facturacion@ordenfacil.org
      - PASSWORD_EMAIL=facturacion*2023
      - HOST_DB=mysql
      - SECRET=awhgedcnqerucvqiuebciqebcdqwygcqucqwejxgq3yrcbq3ce1iyexiqkwjebcq
    volumes:
      # - ./facturacion:/facturacion/src/facturacion_electronica/facturacion/Firmado/
      - ./firma:/facturacion/src/facturacion_electronica/Firma/

  platilla_rides:
    image: djmarret1992/codigobm-plantilla-rides:dev_57956007
    restart: always
    container_name: platilla_rides
    ports:
      - 4031:80
    networks:
      - codigomarret

  crond_pdf:
    image: djmarret1992/codigobm-cron-pdf:dev_6d4459f8
    restart: always
    container_name: crond_pdf
    networks:
      - codigomarret
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - DEV=production
      - USER_DB=root
      - PASSWORD_DB=Marret123456+-*
      - DATABASE_DB=facturacion_api
      - HOST_DB=mysql
      - HOST_PDF=https://ordenfacil.org/pdf/
      - HOST_RIDE=https://ordenfacil.org/rides/rides/
    ports:
      - 4205:3000
    volumes:
      - ./RIDES:/MS/src/public/

  backup:
    image: djmarret1992/codigobm-backup-mysql:dev_w1Qjlkid
    restart: always
    container_name: backup
    networks:
      - codigomarret
    environment:
      - DB_USER=root
      - DB_NAME=facturacion_api
      - DB_PASSWORD=Marret123456+-*
      - DB_HOST=mysql
      - DB_PORT=3306
      - CRON_TIME=59 */5 * * * *
      - TZ=America/Guayaquil
    volumes:
      - ./backup:/BACKUP/up

  upload:
    image: djmarret1992/codigobm-api-upload:dev_WsOjd7wE
    restart: always
    container_name: upload
    networks:
      - codigomarret
    ports:
      - 4206:4000
    environment:
      - PORT=4000
      - DOMINIO=https://codigomarret.online/upload/img/
    volumes:
      - ./upload:/upload/src/public/img

  fromt_autoregistro:
    image: djmarret1992/codigobm-autoregistro-qr:dev_2fcdc669
    restart: always
    container_name: fromt_autoregistro
    networks:
      - codigomarret
    ports:
      - 4207:80

  acortador_link:
    image: djmarret1992/codigobm-acortador-link:v1.8
    restart: always
    container_name: acortador_link
    ports:
      - 4208:8080
    networks:
      - codigomarret
    environment:
      - PORT=8080
      - BASIC_USER=xtrim-link
      - BASIC_PASS=Xtrim*EC2022
      - INSTANCE_URL=https://produccion-tvcable.harperdbcloud.com
      - INSTANCE_USERNAME=grupotvcadmin
      - INSTANCE_PASSWORD=Andresdavid21@
      - INSTANCE_SCHEMA=shortner
      - DOMINIO=https://codigomarret.online/link
      - PATH_KEY_HTTPS=./src/cert/crt.key
      - PATH_CERT_HTTPS=./src/cert/crt.crt
      - DATABASE_URL=mysql://root:Marret123456+-*@161.35.138.208:3382/cortadorlink?schema=public&connection_limit=500&pool_timeout=30



volumes:
  whatsapp_qr: